In [1]:
import torch
print(torch.__version__)

1.13.1+cpu


In [7]:
print(torch.tensor([1,2,3]))
print(torch.tensor([1,2,3], dtype=torch.float64))
print(torch.FloatTensor([1,2,3]))
print(torch.tensor([1,2,3]).to('cpu'))

tensor([1, 2, 3])
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.])
tensor([1, 2, 3])


In [10]:
tensor = torch.tensor([[1,2,3], [4,5,6]])
print(tensor.shape)
print(tensor.size())
print(tensor.dtype)

torch.Size([2, 3])
torch.Size([2, 3])
torch.int64


In [11]:
# list -> tensor
data = [[1,2,3], [4,5,6]]
tensor = torch.tensor(data)

In [14]:
# ndarray -> tensor
# copy
import numpy as np
ndarray = np.array([[1,2,3], [4,5,6]])
tensor = torch.tensor(ndarray)
tensor[0][0] = 4
print(ndarray)
print(tensor)

[[1 2 3]
 [4 5 6]]
tensor([[4, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [16]:
# view 생성
# as_tensor
ndarray = np.array([[1,2,3], [4,5,6]])
tensor = torch.as_tensor(ndarray)
tensor[0][0] = 4
print(ndarray)
print(tensor)

[[4 2 3]
 [4 5 6]]
tensor([[4, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [17]:
# view 생성
# from_numpy
ndarray = np.array([[1,2,3], [4,5,6]])
tensor = torch.from_numpy(ndarray)
tensor[0][0] = 4
print(ndarray)
print(tensor)

[[4 2 3]
 [4 5 6]]
tensor([[4, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [21]:
a = torch.ones(3,3)
b = torch.zeros(3,3)
c = torch.empty(3,3)
d = torch.full((3,3), 2.)
print(a)
print(b)
print(c)
print(d)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [23]:
tensor = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
a = torch.ones_like(tensor)
b = torch.zeros_like(tensor)
c = torch.empty_like(tensor)
d = torch.full_like(tensor, 2.)
print(a)
print(b)
print(c)
print(d)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[32370111954616435, 28147961535004764, 27303467884609653],
        [31244147623002222, 14355640430624878, 33214519704879196],
        [28429402150535283, 28429436511584357, 29555345008492641]])
tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])


In [24]:
identity = torch.eye(3)
identity

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [27]:
a = torch.arange(10)
b = torch.arange(1,10)
c = torch.arange(1,10,2)
print(a)
print(b)
print(c)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([1, 3, 5, 7, 9])


In [32]:
a = torch.rand(3,3) # 0~1 random
b = torch.randn(3,3) # mean 0 std 1 normal distribution
c = torch.randint(1, 15, size=(3,3)) # 0~9 random
print(a)
print(b)
print(c)

tensor([[0.3950, 0.2333, 0.9865],
        [0.8163, 0.0196, 0.8134],
        [0.4626, 0.5571, 0.0779]])
tensor([[ 0.1927,  1.4899, -1.1675],
        [-0.9664,  2.1272,  0.1875],
        [ 0.4024,  1.8164, -0.3679]])
tensor([[ 3,  8,  9],
        [12, 11, 10],
        [ 7,  1,  9]])


In [36]:
# tensor.item()
# scalar 값인 경우에만 원소를 추출
a = torch.tensor([1])
b = torch.tensor([1,2])
print(a)
print(a.item())
print(b.item())

tensor([1])
1


ValueError: only one element tensors can be converted to Python scalars

In [37]:
# reshape()
tensor = torch.arange(12).reshape(3,4)
tensor

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [39]:
# view
# 원본과 데이터를 공유
tensor = torch.arange(12).view(3,4)
tensor

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [53]:
# transpose
# 원본 데이터와 값을 공유
tensor = torch.tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
tensor

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [54]:
tensor2 = tensor.transpose(0,1)
tensor2

tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])

In [55]:
tensor2[0][0] = 100
tensor2

tensor([[100,   5,   9],
        [  2,   6,  10],
        [  3,   7,  11],
        [  4,   8,  12]])

In [56]:
tensor

tensor([[100,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]])

In [57]:
tensor3 = tensor.permute((1, 0))
tensor3

tensor([[100,   5,   9],
        [  2,   6,  10],
        [  3,   7,  11],
        [  4,   8,  12]])

In [58]:
a = torch.tensor([[1,2], [3,4]], dtype=torch.float64)
b = torch.tensor([[4,5], [6,7]], dtype=torch.float64)

In [59]:
print(a+b)
print(a*b)
print(a/b)
print(a-b)
print(a@b)

tensor([[ 5.,  7.],
        [ 9., 11.]], dtype=torch.float64)
tensor([[ 4., 10.],
        [18., 28.]], dtype=torch.float64)
tensor([[0.2500, 0.4000],
        [0.5000, 0.5714]], dtype=torch.float64)
tensor([[-3., -3.],
        [-3., -3.]], dtype=torch.float64)
tensor([[16., 19.],
        [36., 43.]], dtype=torch.float64)


In [60]:
print(torch.add(a,b))
print(torch.subtract(a,b))
print(torch.multiply(a,b))
print(torch.divide(a,b))
print(torch.matmul(a,b))

tensor([[ 5.,  7.],
        [ 9., 11.]], dtype=torch.float64)
tensor([[-3., -3.],
        [-3., -3.]], dtype=torch.float64)
tensor([[ 4., 10.],
        [18., 28.]], dtype=torch.float64)
tensor([[0.2500, 0.4000],
        [0.5000, 0.5714]], dtype=torch.float64)
tensor([[16., 19.],
        [36., 43.]], dtype=torch.float64)


In [61]:
a = torch.arange(12).reshape(3,4)
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [65]:
# indexing
tensor = a[0]
tensor

tensor([0, 1, 2, 3])

In [66]:
# slicing
tensor = a[:1]
tensor

tensor([[0, 1, 2, 3]])

In [68]:
# slicing
tensor = a[0, 1]
tensor

tensor(1)

In [69]:
tensor = a[0, :1]
tensor

tensor([0])

In [70]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [75]:
# 1
tensor = torch.tensor([1,2]).to(device)
print(tensor)

# 2
tensor = torch.tensor([1,2]).cpu()
print(tensor)

# 3
tensor = torch.tensor([1,2], device='cpu')
print(tensor)

tensor.device


tensor([1, 2])
tensor([1, 2])
tensor([1, 2])


device(type='cpu')

In [84]:
# squeeze()
# 차원이 1인 부분을 제거 (default)
tensor = torch.arange(12).reshape(3,1,4)
print(tensor.shape)
tensor = tensor.squeeze()
print(tensor.shape)

tensor = torch.arange(12).reshape(3,1,4,1)
print(tensor.shape)
tensor = tensor.squeeze(dim=1)
print(tensor.shape)


torch.Size([3, 1, 4])
torch.Size([3, 4])
torch.Size([3, 1, 4, 1])
torch.Size([3, 4, 1])


In [86]:
tensor = torch.ones(3,5,7)
print(tensor.shape)
tensor = tensor.unsqueeze(dim=0)
print(tensor.shape)

torch.Size([3, 5, 7])
torch.Size([1, 3, 5, 7])


In [87]:
tensor = torch.arange(12).reshape(3,4)
tensor

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [88]:
a = torch.sum(tensor)
b = torch.sum(tensor, axis=0)
c = torch.sum(tensor, axis=1)
print(a)
print(b)
print(c)

tensor(66)
tensor([12, 15, 18, 21])
tensor([ 6, 22, 38])


In [89]:
m = torch.max(tensor)
m

tensor(11)

In [93]:
m = torch.max(tensor, 1)
print(m)
value, index = torch.max(tensor, 1)
index

torch.return_types.max(
values=tensor([ 3,  7, 11]),
indices=tensor([3, 3, 3]))


tensor([3, 3, 3])

In [95]:
# detach() : gradient 전파가 안되는 view를 생성
# clone() : 복사한 새로운 텐서를 생성
tensor = torch.arange(24).reshape(2,2,6)
a = tensor.detach()
b = tensor.clone()
tensor[0][0][0] = 100
print(a)
print(b)

tensor([[[100,   1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10,  11]],

        [[ 12,  13,  14,  15,  16,  17],
         [ 18,  19,  20,  21,  22,  23]]])
tensor([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]],

        [[12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]]])


In [96]:
tensor = torch.tensor([1,2])
ndarray = tensor.detach().cpu().numpy()
ndarray

array([1, 2], dtype=int64)

In [97]:
a = torch.arange(12).reshape(3,4)
b = torch.arange(12).reshape(3,4)
c = torch.cat([a,b], axis=0)
c

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [98]:
d = torch.cat([a,b], axis=1)
d

tensor([[ 0,  1,  2,  3,  0,  1,  2,  3],
        [ 4,  5,  6,  7,  4,  5,  6,  7],
        [ 8,  9, 10, 11,  8,  9, 10, 11]])